### ISSUE TITLE
Uncapabe of finding the required files

### ISSUE THREAD

**Issue by hantao-zhou** [zhouxian/FluidLab#10]
=> => transferring dockerfile: 785B                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:9.2-devel-ubuntu18.04                                                   0.3s
------
 > [internal] load metadata for docker.io/nvidia/cuda:9.2-devel-ubuntu18.04:
------
Dockerfile:2
--------------------
   1 |     # The docker file is borrowed from https://github.com/columbia-ai-robotics/dextairity
   2 | >>> FROM nvidia/cuda:9.2-devel-ubuntu18.04
   3 |     
   4 |     # Dependencies for glvnd and X11.
--------------------
ERROR: failed to solve: nvidia/cuda:9.2-devel-ubuntu18.04: docker.io/nvidia/cuda:9.2-devel-ubuntu18.04: not found
Unable to find image 'fluidlab-glrenderer:latest' locally
docker: Error response from daemon: pull access denied for fluidlab-glrenderer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
.: datei oder Verzeichnis nicht gefunden: /home/{username}/anaconda3/bin/activate
.: datei oder Verzeichnis nicht gefunden: prepare.sh
.: datei oder Verzeichnis nicht gefunden: compile.sh

**Comment by hantao-zhou** [comment]
❯ sudo docker build -t fluidlab-glrenderer fluidlab/fluidengine/renderers/gl_renderer_src

sudo docker run \
  -v ${PWD}/fluidlab/fluidengine/renderers/gl_renderer_src:/workspace \
  -v /home/{username}/anaconda3:/home/{username}/anaconda3 \
  --gpus all \
  -e DISPLAY=$DISPLAY \
  -e QT_X11_NO_MITSHM=1 \
  -it fluidlab-glrenderer:latest bash

. /home/{username}/anaconda3/bin/activate fluidlab
. prepare.sh
. compile.sh
[+] Building 0.9s (4/4) FINISHED                                                                                           docker:default
 => [internal] load build definition from Dockerfile                                                                                 0.0s
 => => transferring dockerfile: 785B                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:9.2-devel-ubuntu18.04                                                   0.8s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                                           0.0s
------
 > [internal] load metadata for docker.io/nvidia/cuda:9.2-devel-ubuntu18.04:
------
Dockerfile:2
--------------------
   1 |     # The docker file is borrowed from https://github.com/columbia-ai-robotics/dextairity
   2 | >>> FROM nvidia/cuda:9.2-devel-ubuntu18.04
   3 |     
   4 |     # Dependencies for glvnd and X11.
--------------------
ERROR: failed to solve: nvidia/cuda:9.2-devel-ubuntu18.04: docker.io/nvidia/cuda:9.2-devel-ubuntu18.04: not found
Unable to find image 'fluidlab-glrenderer:latest' locally
docker: Error response from daemon: pull access denied for fluidlab-glrenderer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
.: no such file or directory: /home/{username}/anaconda3/bin/activate
.: no such file or directory: prepare.sh
.: no such file or directory: compile.sh

On another system also the same issue

**Comment by hantao-zhou** [comment]
change the docker file to 12.3.1

**Comment by zhouxian** [comment]
Hi, I pushed a commit with an updated file. I verified it's able to pop up the gl renderer window and everything seems to work fine.
