### ISSUE TITLE
Does the codebase need vulkan?

### ISSUE THREAD

**Issue by YoruCathy** [zhouxian/FluidLab#2]
Hi, I'm trying to run the example in the readme file. It is however complaining about no vulkan for ggui. I'm wondering if Taichi requires this for visualization. It would be helpful if some instructions could be added here :)

**Comment by YoruCathy** [comment]
I got the env running (fingers crossed) Is there a document or guide to get started with?

**Comment by zhouxian** [comment]
Did u manage to get it work without vulkan? From https://docs.taichi-lang.org/docs/ggui It seems vulkan is not the only option, but we didn't play a lot with the backend. Regarding the guide: i hope to make one if I find time to work on it, but for now i cannot promise anything apart from the readme file. Feel free to submit a issue if you have any specific question.

**Comment by YoruCathy** [comment]
I figured out how to get it working with vulkan. It did not work before since I'm using webtop remote access to use my desktop and that docker environment causes the problem. I don't have to install it if I directly install it on the desktop.
